#!/usr/bin/env bash
# ============================================================================
# Step 11: Generate & Deploy
# Generate all config files, restart OpenClaw, send first message.
# ============================================================================

wizard_header "11" "Deploy" "Generating configuration and launching your agents..."

# --- Read state ---
USER_NAME="$(state_get 'user.name')"
USER_PREF="$(state_get 'user.preferred_name')"
USER_DOMAIN="$(state_get 'user.domain')"
USER_WORK="$(state_get 'user.current_work')"
BRAIN_NAME="$(state_get 'brain.name' 'Brain')"
BRAIN_STYLE="$(state_get 'brain.style' 'balanced')"
BRAIN_VERBOSITY="$(state_get 'brain.verbosity' 'adaptive')"
BRAIN_NOTES="$(state_get 'brain.personality_notes')"
MEMORY_TIER="$(state_get 'memory_tier' 'standard')"
MESSAGING="$(state_get 'messaging' 'cli')"

MODEL_BRAIN="$(state_get 'models.brain' 'claude-sonnet-4')"
MODEL_BUILDER="$(state_get 'models.builder' 'deepseek-v3')"
MODEL_SCOUT="$(state_get 'models.scout' 'qwen-max')"
MODEL_CHECKER="$(state_get 'models.checker' 'qwen-max')"
MODEL_GUARDIAN="$(state_get 'models.guardian' 'claude-sonnet-4')"

# --- Create directories ---
mkdir -p "$PROJECT_DIR/agents/brain"
mkdir -p "$PROJECT_DIR/agents/builder"
mkdir -p "$PROJECT_DIR/agents/scout"
mkdir -p "$PROJECT_DIR/agents/checker"
mkdir -p "$PROJECT_DIR/agents/guardian"

# ============================================================
# Generate USER.md
# ============================================================
gum spin --spinner dot --title "Generating USER.md..." -- sleep 0.5

cat > "$PROJECT_DIR/USER.md" << EOF
# User Profile

- **Name:** $USER_NAME
- **Call me:** $USER_PREF
- **Domain:** $USER_DOMAIN
$([ -n "$USER_WORK" ] && echo "- **Currently working on:** $USER_WORK")

> This file is read by Brain in main sessions for personalization.
> Do not share in group contexts.
EOF

log_ok "USER.md generated"

# ============================================================
# Generate TEAM.md
# ============================================================
gum spin --spinner dot --title "Generating TEAM.md..." -- sleep 0.5

cat > "$PROJECT_DIR/TEAM.md" << EOF
# Team Context

## Domain
$USER_DOMAIN

## Current Focus
${USER_WORK:-Not specified}

## User
- **Name:** $USER_NAME ($USER_PREF)
- **Field:** $USER_DOMAIN

> This file is shared with ALL agents for domain awareness.
EOF

log_ok "TEAM.md generated"

# ============================================================
# Generate Brain SOUL.md
# ============================================================
gum spin --spinner dot --title "Generating Brain SOUL.md..." -- sleep 0.5

cat > "$PROJECT_DIR/agents/brain/SOUL.md" << SOULEOF
# SOUL.md — $BRAIN_NAME 🧠

## === LOCKED LAYER (DO NOT MODIFY) ===
# These rules are system-critical and not user-configurable.

### Delegation Rules
- Route code tasks to Builder
- Route research to Scout
- Route verification to Checker
- Consult Guardian on safety-sensitive operations

### Context Scoping
- Read USER.md in main sessions only
- Read TEAM.md in all sessions
- Never share USER.md content in group contexts

### Memory Gating
- Write significant events to daily memory files
- Update MEMORY.md periodically with distilled learnings
- Never persist secrets unless explicitly asked

### Safety
- Never reveal internal agent coordination to users
- Never expose other agents' existence unprompted
- Present unified, single-assistant experience

### Response Synthesis
- Integrate sub-agent results into cohesive responses
- Attribute research findings naturally, not mechanically
- Maintain conversation continuity across delegations

## === CUSTOMIZABLE LAYER ===
# Generated by wizard. Re-run \`./wizard.sh --reconfigure\` to change.

### Identity
- **Name:** $BRAIN_NAME
- **Emoji:** 🧠

### Tone
- **Style:** $BRAIN_STYLE
- **Verbosity:** $BRAIN_VERBOSITY

### Personality
${BRAIN_NOTES:-No additional personality notes configured.}
SOULEOF

log_ok "Brain SOUL.md generated"

# ============================================================
# Generate other agent SOUL.md files
# ============================================================

# Builder
cat > "$PROJECT_DIR/agents/builder/SOUL.md" << 'EOF'
# SOUL.md — Builder 🔨

## Role
You are Builder, the code generation and execution specialist.

## Responsibilities
- Write clean, well-tested code
- Execute code in sandboxed environments
- Handle file system operations
- Manage git operations and deployments

## Behavior
- Read TEAM.md for domain context
- Communicate results clearly to Brain
- Prioritize working code over perfect code
- Include error handling and edge cases
- Comment complex logic
EOF

# Scout
cat > "$PROJECT_DIR/agents/scout/SOUL.md" << 'EOF'
# SOUL.md — Scout 🔬

## Role
You are Scout, the research and synthesis specialist.

## Responsibilities
- Search the web for relevant information
- Synthesize findings into clear summaries
- Verify source credibility
- Provide citations and links

## Behavior
- Read TEAM.md for domain context
- Focus on accuracy and relevance
- Present findings in a structured format
- Flag conflicting information
- Prioritize recent and authoritative sources
EOF

# Checker
cat > "$PROJECT_DIR/agents/checker/SOUL.md" << 'EOF'
# SOUL.md — Checker ✅

## Role
You are Checker, the fact verification and accuracy specialist.

## Responsibilities
- Verify claims and statements for accuracy
- Cross-reference multiple sources
- Check code for correctness and best practices
- Validate data and calculations

## Behavior
- Read TEAM.md for domain context
- Be precise and detail-oriented
- Clearly state confidence levels
- Flag uncertainties explicitly
- Provide evidence for corrections
EOF

# Guardian
cat > "$PROJECT_DIR/agents/guardian/SOUL.md" << 'EOF'
# SOUL.md — Guardian 🛡️

## Role
You are Guardian, the security and safety specialist.

## Responsibilities
- Review operations for security implications
- Validate API keys and credentials handling
- Check for data privacy concerns
- Assess risk of proposed actions

## Behavior
- Read TEAM.md for domain context
- Default to caution on ambiguous situations
- Provide clear risk assessments
- Suggest safer alternatives when needed
- Never allow credential exposure
EOF

log_ok "Agent SOUL.md files generated"

# ============================================================
# Generate agent config.yaml files
# ============================================================
gum spin --spinner dot --title "Generating agent configs..." -- sleep 0.5

# Helper to generate agent config
gen_agent_config() {
    local agent="$1" model="$2" role="$3"
    cat > "$PROJECT_DIR/agents/$agent/config.yaml" << EOF
# $agent agent configuration
# Generated by setup wizard

agent:
  name: $agent
  model: $model
  role: $role
  soul: agents/$agent/SOUL.md
  context:
    - TEAM.md
    - AGENTS.md
EOF
}

gen_agent_config "brain"    "$MODEL_BRAIN"    "orchestrator"
gen_agent_config "builder"  "$MODEL_BUILDER"  "code"
gen_agent_config "scout"    "$MODEL_SCOUT"    "research"
gen_agent_config "checker"  "$MODEL_CHECKER"  "verification"
gen_agent_config "guardian" "$MODEL_GUARDIAN"  "security"

# Add Brain-specific config
cat >> "$PROJECT_DIR/agents/brain/config.yaml" << EOF
  personal_context:
    - USER.md
  delegates:
    - builder
    - scout
    - checker
    - guardian
  channel: $MESSAGING
EOF

log_ok "Agent configs generated"

# ============================================================
# Generate openclaw.yaml
# ============================================================
gum spin --spinner dot --title "Generating openclaw.yaml..." -- sleep 0.5

TOOLS_LIST="$(state_get 'tools' '["file_access"]')"

cat > "$PROJECT_DIR/openclaw.yaml" << EOF
# OpenClaw Gateway Configuration
# Generated by setup wizard — $(date -u +%Y-%m-%dT%H:%M:%SZ)

gateway:
  port: 3000
  workspace: $PROJECT_DIR

agents:
  brain:
    config: agents/brain/config.yaml
    primary: true
  builder:
    config: agents/builder/config.yaml
  scout:
    config: agents/scout/config.yaml
  checker:
    config: agents/checker/config.yaml
  guardian:
    config: agents/guardian/config.yaml

memory:
  tier: $MEMORY_TIER

messaging:
  platform: $MESSAGING
$(case "$MESSAGING" in
    telegram) echo "  telegram_token: \$(state_get 'telegram_token')" ;;
    discord)  echo "  discord_token: \$(state_get 'discord_token')" ; echo "  discord_guild: \$(state_get 'discord_guild_id')" ;;
    signal)   echo "  signal_phone: \$(state_get 'signal_phone')" ;;
esac)

tools: $TOOLS_LIST
EOF

log_ok "openclaw.yaml generated"

# ============================================================
# Ensure .gitignore excludes sensitive files
# ============================================================
if ! grep -q '.wizard-state.json' "$PROJECT_DIR/.gitignore" 2>/dev/null; then
    echo '.wizard-state.json' >> "$PROJECT_DIR/.gitignore"
fi

# ============================================================
# Restart OpenClaw
# ============================================================
wizard_divider
log_info "Restarting OpenClaw..."

if has_cmd systemctl && systemctl is-enabled --quiet openclaw.service 2>/dev/null; then
    gum spin --spinner dot --title "Restarting OpenClaw service..." -- sudo systemctl restart openclaw.service
    sleep 3
    if systemctl is-active --quiet openclaw.service; then
        log_ok "OpenClaw service restarted"
    else
        log_warn "Service may still be starting"
    fi
elif has_cmd openclaw; then
    gum spin --spinner dot --title "Starting OpenClaw gateway..." -- openclaw gateway restart 2>/dev/null || openclaw gateway start 2>/dev/null || true
    log_ok "OpenClaw gateway started"
else
    log_warn "OpenClaw not found — please start it manually"
fi

# ============================================================
# Summary
# ============================================================
wizard_divider

gum style \
    --border rounded \
    --border-foreground 2 \
    --padding "1 3" \
    --margin "0 2" \
    --bold \
    "🎉 Deployment Complete!" \
    "" \
    "  👤 User:     $USER_NAME ($USER_PREF)" \
    "  🧠 Brain:    $BRAIN_NAME ($MODEL_BRAIN)" \
    "  🔨 Builder:  $MODEL_BUILDER" \
    "  🔬 Scout:    $MODEL_SCOUT" \
    "  ✅ Checker:  $MODEL_CHECKER" \
    "  🛡️ Guardian: $MODEL_GUARDIAN" \
    "  💾 Memory:   $MEMORY_TIER" \
    "  💬 Channel:  $MESSAGING" \
    "" \
    "  $BRAIN_NAME is online and ready!"

echo ""
log_info "To reconfigure later: ./wizard/wizard.sh --reconfigure"
log_info "Config files are in: $PROJECT_DIR"

wizard_success "Your multi-agent system is live! 🚀"
